[2022-06-02 09:13:28,330] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: todoist_load_to_pg.task_get_proj scheduled__2022-06-01T00:00:00+00:00 [queued]>
[2022-06-02 09:13:28,353] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: todoist_load_to_pg.task_get_proj scheduled__2022-06-01T00:00:00+00:00 [queued]>
[2022-06-02 09:13:28,357] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 09:13:28,358] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-06-02 09:13:28,358] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 09:13:28,387] {taskinstance.py:1264} INFO - Executing <Task(SimpleHttpOperator): task_get_proj> on 2022-06-01 00:00:00+00:00
[2022-06-02 09:13:28,392] {standard_task_runner.py:52} INFO - Started process 76 to run task
[2022-06-02 09:13:28,401] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'todoist_load_to_pg', 'task_get_proj', 'scheduled__2022-06-01T00:00:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/todoist_load_to_pg.py', '--cfg-path', '/tmp/tmp6ngvgdx1', '--error-file', '/tmp/tmpru04w148']
[2022-06-02 09:13:28,402] {standard_task_runner.py:77} INFO - Job 400: Subtask task_get_proj
[2022-06-02 09:13:28,482] {logging_mixin.py:109} INFO - Running <TaskInstance: todoist_load_to_pg.task_get_proj scheduled__2022-06-01T00:00:00+00:00 [running]> on host bd658c040114
[2022-06-02 09:13:28,541] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=emil
AIRFLOW_CTX_DAG_ID=todoist_load_to_pg
AIRFLOW_CTX_TASK_ID=task_get_proj
AIRFLOW_CTX_EXECUTION_DATE=2022-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-01T00:00:00+00:00
[2022-06-02 09:13:28,542] {http.py:104} INFO - Calling HTTP method
[2022-06-02 09:13:28,555] {base.py:70} INFO - Using connection to: id: todo_conn. Host: https://api.todoist.com/rest/v1, Port: None, Schema: , Login: admin, Password: ***, extra: {}
[2022-06-02 09:13:28,559] {http.py:129} INFO - Sending 'GET' to url: https://api.todoist.com/rest/v1/projects
[2022-06-02 09:13:29,040] {http.py:142} ERROR - HTTP error: Forbidden
[2022-06-02 09:13:29,041] {http.py:143} ERROR - <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>403 - Sorry, you are forbidden to access this</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="canonical" href="https://api.todoist.com/rest/v1/projects?lang=en" />
<link rel="alternate" hreflang="x-default" href="https://api.todoist.com/rest/v1/projects" />
<link rel="alternate" hreflang="cs" href="https://api.todoist.com/rest/v1/projects?lang=cs" />
<link rel="alternate" hreflang="da" href="https://api.todoist.com/rest/v1/projects?lang=da" />
<link rel="alternate" hreflang="en" href="https://api.todoist.com/rest/v1/projects?lang=en" />
<link rel="alternate" hreflang="de" href="https://api.todoist.com/rest/v1/projects?lang=de" />
<link rel="alternate" hreflang="es" href="https://api.todoist.com/rest/v1/projects?lang=es" />
<link rel="alternate" hreflang="fi" href="https://api.todoist.com/rest/v1/projects?lang=fi" />
<link rel="alternate" hreflang="fr" href="https://api.todoist.com/rest/v1/projects?lang=fr" />
<link rel="alternate" hreflang="it" href="https://api.todoist.com/rest/v1/projects?lang=it" />
<link rel="alternate" hreflang="nl" href="https://api.todoist.com/rest/v1/projects?lang=nl" />
<link rel="alternate" hreflang="nb" href="https://api.todoist.com/rest/v1/projects?lang=nb" />
<link rel="alternate" hreflang="pl" href="https://api.todoist.com/rest/v1/projects?lang=pl" />
<link rel="alternate" hreflang="pt-_BR" href="https://api.todoist.com/rest/v1/projects?lang=pt_BR" />
<link rel="alternate" hreflang="ru" href="https://api.todoist.com/rest/v1/projects?lang=ru" />
<link rel="alternate" hreflang="tr" href="https://api.todoist.com/rest/v1/projects?lang=tr" />
<link rel="alternate" hreflang="sv" href="https://api.todoist.com/rest/v1/projects?lang=sv" />
<link rel="alternate" hreflang="zh-_TW" href="https://api.todoist.com/rest/v1/projects?lang=zh_TW" />
<link rel="alternate" hreflang="zh-_CN" href="https://api.todoist.com/rest/v1/projects?lang=zh_CN" />
<link rel="alternate" hreflang="ko" href="https://api.todoist.com/rest/v1/projects?lang=ko" />
<link rel="alternate" hreflang="ja" href="https://api.todoist.com/rest/v1/projects?lang=ja" />

    <style type="text/css">
    body{
        text-align:center;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        font-size:small;
        color:#555;
        line-height: 20px;
    }

    h3 {
        font-size: 25px;
        line-height: 30px;
        font-weight: normal;
    }

    a {
        color: #db4c3f;
        text-decoration: none;
    }

    p {
        font-size:14px;
        margin:8px 0 0;
    }

    #container{
        margin:53px auto;
        max-width:400px;
        text-align:left;
        padding: 20px;
        background:#fff;
    }

    .logo {
        margin-bottom: 60px;
        margin-top: 0;
    }

    .button {
      border: 0;
      border-radius: 3px;
      font-size: 14px;
      font-weight: 600;
      letter-spacing: 0.05em;
      line-height: 1.2;
      padding: 10px 15px;
      color: white;
      cursor: pointer;
      background-color: #db4c3f;
      display: inline-block;
      margin-bottom: 10px;
    }

    .buttons {
      margin-top: 50px;
      text-align: center;
    }
    </style>

</head>

<body>

<body>




<div id="container">
    <p class="logo">
        <a href="https://todoist.com/">
            <img src="https://d3ptyyxy2at9ui.cloudfront.net/logo-todoist-b5b89f.svg" height="35" />
        </a>
    </p>

        <h3>Invalid format for Authentication header</h3>

        <p>
            

            If you reached this page from another part of <a href="https://todoist.com/">todoist.com</a>,
            please <a href="https://get.todoist.help/">let us know</a> so we can correct our mistake.
        </p>
</div>

</body>

</body>
</html>

[2022-06-02 09:13:29,056] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 140, in check_response
    response.raise_for_status()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.todoist.com/rest/v1/projects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 106, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 130, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 183, in run_and_check
    self.check_response(response)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 144, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2022-06-02 09:13:29,067] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=todoist_load_to_pg, task_id=task_get_proj, execution_date=20220601T000000, start_date=20220602T091328, end_date=20220602T091329
[2022-06-02 09:13:29,083] {standard_task_runner.py:89} ERROR - Failed to execute job 400 for task task_get_proj
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 140, in check_response
    response.raise_for_status()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.todoist.com/rest/v1/projects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 106, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 130, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 183, in run_and_check
    self.check_response(response)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 144, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 403:Forbidden
[2022-06-02 09:13:29,110] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-02 09:13:29,147] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
